---
services: docker

env:
  - distro: centos7

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Ensure Vagrant is installed.
  - 'docker exec --tty ${container_id} env TERM=xterm which vagrant'
  - 'docker exec --tty ${container_id} env TERM=xterm vagrant list-commands'
  - 'docker exec --tty ${container_id} env TERM=xterm ls /root/vagrant/infraci/Vagrantfile'
  - 'docker exec --tty ${container_id} env TERM=xterm sh -c "cd /root/vagrant/infraci/ && vagrant validate"'

