---
- name: Ensure temp download directory exist
  file:
    state: directory
    path: "{{ vagrant_tmp_dir }}"

- name: Download vagrant
  get_url:
    url: "{{ vagrant_url_rpm }}"
    dest: "{{ vagrant_tmp_rpm }}"
    checksum: "sha256:{{ vagrant_checksum_sha256 }}"

- name: Install vagrant for RedHat OS family
  yum:
    name: "{{ vagrant_tmp_rpm }}"

